using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http.Connections;

namespace Plutus.Web.Authentication;

/// <summary>
/// Applies transport options to the hub endpoints generated by Razor Components.
/// Adding a second MapBlazorHub route is incorrect for a Blazor Web App because
/// Razor Components already creates that route.
/// </summary>
public static class InteractiveServerTransportSecurity
{
    public static RazorComponentsEndpointConventionBuilder CloseConnectionsOnAuthenticationExpiration(
        this RazorComponentsEndpointConventionBuilder endpoints)
    {
        endpoints.Add(endpoint =>
        {
            foreach (var connectionOptions in endpoint.Metadata.OfType<HttpConnectionDispatcherOptions>())
            {
                connectionOptions.CloseOnAuthenticationExpiration = true;
            }
        });

        return endpoints;
    }
}
