// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plutus.Core.Data;

#nullable disable

namespace Plutus.Core.Data.Migrations
{
    [DbContext(typeof(PlutusDbContext))]
    partial class PlutusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Plutus.Core.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Balance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BalanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Org")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimpleFinAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SimpleFinAccountId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Plutus.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#16A34A",
                            IsSystem = true,
                            Name = "Groceries",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#EA580C",
                            IsSystem = true,
                            Name = "Dining",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#0891B2",
                            IsSystem = true,
                            Name = "Transport",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Color = "#7C3AED",
                            IsSystem = true,
                            Name = "Shopping",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Color = "#CA8A04",
                            IsSystem = true,
                            Name = "Utilities",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Color = "#0D9488",
                            IsSystem = true,
                            Name = "Housing",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Color = "#DC2626",
                            IsSystem = true,
                            Name = "Health",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            Color = "#DB2777",
                            IsSystem = true,
                            Name = "Entertainment",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            Color = "#2563EB",
                            IsSystem = true,
                            Name = "Travel",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            Color = "#9333EA",
                            IsSystem = true,
                            Name = "Subscriptions",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 11,
                            Color = "#64748B",
                            IsSystem = true,
                            Name = "Fees",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 12,
                            Color = "#6B7280",
                            IsSystem = true,
                            Name = "Other",
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("Plutus.Core.Models.SimpleFinConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SimpleFinConnections");
                });

            modelBuilder.Entity("Plutus.Core.Models.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RanAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RanAt");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("Plutus.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CategorizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCategorized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimpleFinTransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsReviewed");

                    b.HasIndex("PostedDate");

                    b.HasIndex("SimpleFinTransactionId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Plutus.Core.Models.Transaction", b =>
                {
                    b.HasOne("Plutus.Core.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plutus.Core.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Plutus.Core.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Plutus.Core.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
